# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: 
          name: install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: lint
          command: npm run lint
      
      - run:
          name: test
          command: npm run test -- --coverage

      # Uncomment if using codacy code coverage
      # - run:
      #     name: coverage
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         cat ./coverage/lcov.info | node_modules/.bin/codacy-coverage -p .
      #       fi